apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-api-beta
  labels:
    app: rs-api-beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rs-api-beta
  template:
    metadata:
      labels:
        app: rs-api-beta
    spec:
      containers:
      - name: rs-api-beta
        image: julianpoy/recipesage:api-$RELEASE_TAG
        ports:
        - containerPort: 3000
        command: ["tsx"]
        args: ["packages/backend/src/bin/www"]
        resources:
          requests:
            cpu: 250m
            memory: 300Mi
          limits:
            cpu: 1
            memory: 1G
        envFrom:
        - secretRef:
            name: rs-api-env
        env:
        - name: BROWSERLESS_HOST
          value: "rs-browserless"
        - name: BROWSERLESS_PORT
          value: "3000"
        - name: INGREDIENT_INSTRUCTION_CLASSIFIER_URL
          value: http://rs-ingredient-instruction-classifier:3000/
        - name: SEARCH_PROVIDER
          value: elasticsearch
        - name: STORAGE_TYPE
          value: s3
        volumeMounts:
        - name: firebase-credentials
          mountPath: /app/Backend/src/config/firebase-credentials.json
          subPath: firebase-credentials.json
      volumes:
        - name: firebase-credentials
          configMap:
            name: firebase-credentials
      imagePullSecrets:
      - name: myregistrykey
      terminationGracePeriodSeconds: 900
---
apiVersion: v1
kind: Service
metadata:
  name: rs-api-beta
spec:
  type: ClusterIP
  selector:
    app: rs-api-beta
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

