apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rs-elastic
spec:
  serviceName: rs-elastic
  replicas: 1
  selector:
    matchLabels:
      app: rs-elastic
  template:
    metadata:
      labels:
        app: rs-elastic
    spec:
      initContainers:
      - name: rs-elastic-chown
        image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
        command: ["chown", "-v", "elasticsearch:elasticsearch", "/usr/share/elasticsearch/data"]
        resources:
          requests:
            cpu: 0.1
            memory: 100Mi
          limits:
            cpu: 0.1
            memory: 500Mi
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      containers:
      - name: rs-elastic
        image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
        env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: -Xms1500m -Xmx1500m
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rs-elastic-env
              key: ELASTIC_PASSWORD
        ports:
          - containerPort: 9200
            name: http
            protocol: TCP
        resources:
          requests:
            cpu: 0.5
            memory: 2Gi
          limits:
            cpu: 1.5
            memory: 3Gi
        volumeMounts:
        # - name: config
        #   mountPath: /usr/share/elasticsearch/elasticsearch.yml
        #   subPath: elasticsearch.yml
        - name: data
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: elasticsearch-data
---
apiVersion: v1
kind: Service
metadata:
  name: rs-elastic
spec:
  type: ClusterIP
  selector:
    app: rs-elastic
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage
